language: php
php:
  - '7.2'
  - '7.3'

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - phpenv rehash
  - nvm install 12.13.1
  - npm install npm@latest -g
  - npm install -g jshint
  - npm install
  - sudo mysql -e 'create database boojbooks'
  - php artisan migrate

script:
  - vendor/bin/phpunit --coverage-text
  - npm run production
  - jshint resources/assets/js/modules/*
